import { AIProvider, BusinessProfile, StrategyResult } from "../types";

export const mockProvider: AIProvider = "mock";

export async function callMockProvider(
  profile: BusinessProfile
): Promise<StrategyResult> {
  const { name, industry, country, budget } = profile;

  return {
    overview: {
      businessName: name,
      industry,
      country,
      budget,
      marketScore: 78,
      growthPotential: "High",
      competition: "Medium",
      estimatedROI: "280%",
      budgetSplit: { meta: 40, google: 30, tiktok: 15, linkedin: 10, other: 5 },
    },
    market: {
      marketSize: "$4.2B",
      growthRate: 12.5,
      trends: ["AI integration", "Mobile-first", "Sustainability"],
      opportunities: ["Underserved niches", "B2B expansion", "International markets"],
      threats: ["New competitors", "Regulatory changes", "Economic downturn"],
      customerPainPoints: ["High costs", "Complex solutions", "Poor support"],
      buyingMotivations: ["ROI", "Ease of use", "Reliability"],
    },
    competitors: [
      {
        name: "Market Leader Co",
        website: "leader.com",
        share: "35%",
        traffic: "250K/mo",
        ads: "Very Active",
        position: "Leader",
        strengths: ["Brand recognition", "Large budget", "Established presence"],
        weaknesses: ["Slow to innovate", "High prices", "Poor customer service"],
        opportunity: 72,
        estimatedTraffic: 250000,
        seoVisibility: 88,
        topChannels: ["Google", "Meta", "LinkedIn"],
        mainOffer: "Premium solution",
        uniqueSellingProposition: "Industry standard",
        customerSentiment: "positive",
        growthScore: 75,
        trendScore: 65,
        competitiveThreat: "high",
        advertisingActivity: { googleAds: true, metaAds: true, linkedinAds: true, tiktokAds: false },
      },
      {
        name: "Challenger Brand",
        website: "challenger.com",
        share: "18%",
        traffic: "120K/mo",
        ads: "Active",
        position: "Challenger",
        strengths: ["Innovative", "Good pricing", "Strong social presence"],
        weaknesses: ["Limited budget", "Smaller team", "Less experience"],
        opportunity: 65,
        estimatedTraffic: 120000,
        seoVisibility: 72,
        topChannels: ["Meta", "TikTok", "Instagram"],
        mainOffer: "Affordable alternative",
        uniqueSellingProposition: "Best value for money",
        customerSentiment: "neutral",
        growthScore: 82,
        trendScore: 78,
        competitiveThreat: "medium",
        advertisingActivity: { googleAds: true, metaAds: true, linkedinAds: false, tiktokAds: true },
      },
      {
        name: "Niche Player",
        website: "niche.com",
        share: "8%",
        traffic: "45K/mo",
        ads: "Moderate",
        position: "Niche",
        strengths: ["Specialized expertise", "Loyal customer base", "High quality"],
        weaknesses: ["Limited reach", "Small market", "Scaling issues"],
        opportunity: 58,
        estimatedTraffic: 45000,
        seoVisibility: 65,
        topChannels: ["Google", "Email"],
        mainOffer: "Specialized solution",
        uniqueSellingProposition: "Expert in one thing",
        customerSentiment: "positive",
        growthScore: 60,
        trendScore: 55,
        competitiveThreat: "low",
        advertisingActivity: { googleAds: true, metaAds: false, linkedinAds: true, tiktokAds: false },
      },
    ],
    audience: {
      primaryPersona: {
        name: "Decision Maker Dan",
        age: "35-50",
        gender: "Any",
        income: "$80K-$150K",
        occupation: "Business Owner / Marketing Director",
        goals: ["Increase ROI", "Scale business", "Reduce costs"],
        painPoints: ["Wasted ad spend", "Lack of insights", "Time constraints"],
        preferredChannels: ["LinkedIn", "Google", "Email"],
        buyingBehavior: "Research-driven, compares options carefully",
      },
      secondaryPersona: {
        name: "Growth Hacker Gina",
        age: "25-35",
        gender: "Any",
        income: "$50K-$90K",
        occupation: "Marketing Manager / Growth Lead",
        goals: ["Quick wins", "Data-driven decisions", "Career growth"],
        painPoints: ["Limited budget", "Tool overload", "Proving ROI"],
        preferredChannels: ["Twitter", "Reddit", "YouTube"],
        buyingBehavior: "Fast decision maker, tries new tools often",
      },
      demographics: {
        location: country,
        language: "English",
        device: "Mobile 60%, Desktop 40%",
        timezone: "Business hours peak",
      },
      behaviors: ["Research online before buying", "Read reviews", "Compare pricing"],
      interests: ["Marketing automation", "AI tools", "Business growth", "Analytics"],
    },
    personas: [
      {
        name: "Decision Maker Dan",
        age: "35-50",
        gender: "Any",
        income: "$80K-$150K",
        occupation: "Business Owner",
        goals: ["Increase ROI", "Scale business"],
        painPoints: ["Wasted ad spend", "Lack of insights"],
        preferredChannels: ["LinkedIn", "Google"],
        buyingBehavior: "Research-driven",
      },
      {
        name: "Growth Hacker Gina",
        age: "25-35",
        gender: "Any",
        income: "$50K-$90K",
        occupation: "Marketing Manager",
        goals: ["Quick wins", "Data-driven decisions"],
        painPoints: ["Limited budget", "Tool overload"],
        preferredChannels: ["Twitter", "Reddit"],
        buyingBehavior: "Fast decision maker",
      },
    ],
    campaigns: [
      {
        platform: "Meta",
        headline: `Transform Your ${industry} Strategy`,
        text: `Join thousands of ${industry} businesses in ${country} growing with data-driven marketing.`,
        cta: "Get Started",
        hook: "Problem-Agitate-Solve",
        objective: "Awareness",
        budget: `$${Math.round(budget * 0.4)}`,
        reach: "50K-100K",
        targetPersona: "Decision Maker Dan",
        duration: "Ongoing",
      },
      {
        platform: "Google",
        headline: `Best ${industry} Solution in ${country}`,
        text: "Get measurable results with our proven marketing framework. Free consultation available.",
        cta: "Learn More",
        hook: "Search Intent",
        objective: "Conversion",
        budget: `$${Math.round(budget * 0.3)}`,
        reach: "20K-50K",
        targetPersona: "Decision Maker Dan",
        duration: "Ongoing",
      },
      {
        platform: "TikTok",
        headline: "Marketing Made Simple",
        text: "Watch how we helped 500+ businesses 3x their ROI in 90 days.",
        cta: "Watch Now",
        hook: "Social Proof",
        objective: "Engagement",
        budget: `$${Math.round(budget * 0.15)}`,
        reach: "100K+",
        targetPersona: "Growth Hacker Gina",
        duration: "3 months",
      },
      {
        platform: "LinkedIn",
        headline: "The Future of Marketing is Here",
        text: "Discover AI-powered strategies that deliver real results for your business.",
        cta: "Download Guide",
        hook: "Thought Leadership",
        objective: "Lead Generation",
        budget: `$${Math.round(budget * 0.1)}`,
        reach: "10K-25K",
        targetPersona: "Decision Maker Dan",
        duration: "Ongoing",
      },
    ],
    creative: {
      adCopy: [
        {
          platform: "Meta",
          headline: `Stop Wasting Ad Spend`,
          primaryText: `Most ${industry} businesses lose 40% of their ad budget. We help you recover it with data-driven strategies.`,
          cta: "Get Free Audit",
          hook: "Pain Point",
          tone: "Authoritative",
        },
        {
          platform: "Google",
          headline: `${industry} Marketing That Works`,
          primaryText: "Proven strategies. Real results. No fluff. See how we delivered 280% ROI for businesses like yours.",
          cta: "See Case Studies",
          hook: "Social Proof",
          tone: "Professional",
        },
        {
          platform: "TikTok",
          headline: "POV: Your Marketing Finally Works",
          primaryText: "The secret that 500+ businesses use to 3x their ROI. Hint: it's not what you think.",
          cta: "Learn the Secret",
          hook: "Curiosity",
          tone: "Casual",
        },
      ],
      visualDirection: "Clean, modern, professional with bold accent colors",
      brandVoice: "Confident, helpful, data-driven",
      colorPalette: ["#6366f1", "#8b5cf6", "#10b981", "#f59e0b", "#1f2937"],
    },
    analytics: {
      kpis: [
        { name: "ROI", target: "280%", trend: "up" },
        { name: "CAC", target: "<$50", trend: "down" },
        { name: "Conversion Rate", target: ">3.5%", trend: "up" },
        { name: "CTR", target: ">2.5%", trend: "up" },
        { name: "LTV", target: ">$500", trend: "up" },
      ],
      trackingSetup: [
        "Google Analytics 4",
        "Meta Pixel",
        "LinkedIn Insight Tag",
        "UTM parameters",
        "Conversion API",
      ],
      reportingCadence: "Weekly performance reports + Monthly strategic review",
    },
    roadmap: [
      {
        month: "Month 1",
        task: "Foundation & Setup",
        priority: "High",
        impact: "Critical",
        difficulty: "Medium",
        results: "All tracking in place, campaigns ready to launch",
      },
      {
        month: "Month 2",
        task: "Launch & Test",
        priority: "High",
        impact: "High",
        difficulty: "Low",
        results: "First campaigns live, initial data collection",
      },
      {
        month: "Month 3",
        task: "Optimize & Scale",
        priority: "Medium",
        impact: "High",
        difficulty: "Medium",
        results: "Winning ads identified, budget reallocation",
      },
      {
        month: "Month 4-6",
        task: "Expand & Dominate",
        priority: "Medium",
        impact: "Very High",
        difficulty: "High",
        results: "Multi-channel presence, positive ROI",
      },
    ],
    recommendations: [
      {
        category: "positioning",
        priority: "high",
        title: "Differentiate on Value",
        description: `Position ${name} as the data-driven alternative in the ${industry} space in ${country}.`,
        expectedImpact: "+35% conversion rate",
        effort: "medium",
        confidence: 87,
      },
      {
        category: "channels",
        priority: "high",
        title: "Focus on Meta + Google",
        description: "Allocate 70% of budget to Meta and Google for maximum reach and intent capture.",
        expectedImpact: "+50% visibility",
        effort: "low",
        confidence: 92,
      },
      {
        category: "creative",
        priority: "medium",
        title: "Video-First Content",
        description: "Create short-form video content for TikTok and Reels to capture attention.",
        expectedImpact: "+40% engagement",
        effort: "medium",
        confidence: 78,
      },
      {
        category: "budget",
        priority: "high",
        title: "Optimize Ad Spend",
        description: "Use automated bidding and audience segmentation to reduce CAC by 30%.",
        expectedImpact: "-30% CAC",
        effort: "low",
        confidence: 85,
      },
    ],
    aiRecommendation: {
      opportunity: `Focus on Meta Ads for ${industry} in ${country} with video-first creative`,
      confidence: "87%",
      result: "+40% reach and +25% conversion in 90 days",
      priority: "High",
    },
  };
}